profile:
  parameters:
    gcp_project_id: <your-gcp-project-id>
    bigquery_dataset: QUICKSTART_DEV
    bigquery_location: US

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: bigquery_data_plane
