profile:
  parameters:
    snowflake:
      account: <your-snowflake-account>
      user: ASCEND_ENV_DEV
      database: ASCEND_ENV_DEV
      schema: ASCEND_ENV_DEV
      warehouse: ASCEND_ENV_DEV
      role: ASCEND_ENV_DEV

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
