component:
  read:
    connection: local_files
    local_file:
      path: /routes.csv
      parser:
        csv:
          has_header: true
  tests:
    columns:
      route_id:
        - not_null
        - unique
      route_name:
        - not_null
