profile:
  parameters:

    snowflake:
      # Snowflake account
      # e.g. account: wvwohks-syb91821
      account: <your-snowflake-account>

      # adjust the values below if needed
      user: ASCEND_ENV_DEV
      database: ASCEND_ENV_DEV
      schema: ASCEND_ENV_DEV
      warehouse: ASCEND_ENV_DEV
      role: ASCEND_ENV_DEV

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
