profile:
  parameters:

    snowflake:
      # Snowflake account
      # e.g. account: wvwohks-syb91821
      account: maritz-atl_rd

      # adjust the values below if needed
      user: SERVICE_ASCEND_GEN3
      database: ASCEND_GEN3_DATAPLANE
      schema: INSTANCE_DATA
      warehouse: WH_ASCEND_GEN3
      role: ASCEND_GEN3_DATAPLANE_DBA

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
