profile:
  parameters:

    warehouse:
      # like 'xxx-yyy.datawarehouse.fabric.microsoft.com'
      server: <your-warehouse-host>
      # If you chose a different name for the warehouse, use that below
      name: ascend_data_plane_warehouse
      # If you chose a different schema for the warehouse, use that below
      schema: quickstart

    service_principal:
      # client_id is the same as appId in various places in Azure
      client_id: <your-client-id>
      # tenant_id is sometimes tenant or directory id in Azure
      tenant_id: <your-tenant-id>

    storage_account:
      name: <your-storage-account-name>
      # If you chose a different path for the storage container name, use that below
      path: "abfss://ascend-staging"

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: fabric_data_plane
