name: ottos-expeditions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  # push:
  #   branches: ["main"]
  #   paths:
  #     - "ottos-expeditions/**"
  #     - ".github/workflows/ottos-expeditions.yaml"

concurrency:
  group: "ottos-expeditions"
  cancel-in-progress: false

jobs:
  datagen:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: checkout
        uses: actions/checkout@v4

      # install Python and just and uv
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: extractions/setup-just@v1
      - uses: astral-sh/setup-uv@v5

      # install ottos-expeditions
      - run: just install

      # run datagen
      - run: ottos-expeditions datagen --days 7

